[package]
name = "benchmark"
version = "0.3.1"
authors = ["Kay-Uwe Kirstein <kay-uwe@kirsteinhome.ch>"]
edition = "2018"

[dependencies]
num = "^0.4"
num-complex = "^0.4"
image = "^0.23"
rayon = "^1.0"
rand = {version = "^0.8.3", features = ["small_rng"]}

