name = "my_hello_world"
description = "Hello world tutorial"
version = "0.1.0-dev"

authors = ["Kay-Uwe Kirstein"]
maintainers = ["Kay-Uwe Kirstein <kay-uwe@kirsteinhome.ch>"]
maintainers-logins = ["kkirstein"]
licenses = "MIT"
website = ""
tags = ["tutorial"]

executables = ["my_hello_world"]
