name = "command_line_arguments"
description = "Tutorial to parse command line arguments"
version = "0.1.0-dev"

authors = ["Kay-Uwe Kirstein"]
maintainers = ["Kay-Uwe Kirstein <kay-uwe@kirsteinhome.ch>"]
maintainers-logins = ["kkirstein"]
licenses = "MIT"
website = ""
tags = ["tutorial"]

executables = ["command_line_arguments"]
